Encapsulation
taras-lytovchenko/Java_application pull request #6
Opened 2022-06-06 17:49 UTC by TLdinam

2022-06-10 21:31 UTC, taraskarpenko requested changes
Идея инкапсуляции состоит в том что метод находящийся в классе работает только с полями текушего екземпляра, а у вас в многие методы передается StudentsGroup.
Технически так конечно будет работать, но тогда такие методы можно даже вынести в любой другой класс или сделать статическими, так как они по сути отделены от екземпляра.

2022-06-10 21:31 UTC, taraskarpenko commented on src/main/java/Student.java
> +    private int StudentId;
Не стоит использовать первую заглавную букву в именах полей

2022-06-10 21:31 UTC, taraskarpenko commented on src/main/java/StudentsGroup.java
> +    public void changeCaptain(String name, StudentsGroup studentsGroup) {
По логике этот метод должен устанавливать старосту только для своего екземпляра, тут studentsGroup входящий параметр лишний

Ну и для установки старосты полагаться на имя студента даже без фамилии как-то не очень надежно

2022-06-13 12:03 UTC, TLdinam commented on src/main/java/Student.java
> +    private int StudentId;
fixed

2022-06-13 12:03 UTC, TLdinam commented on src/main/java/StudentsGroup.java
> +    public void changeCaptain(String name, StudentsGroup studentsGroup) {
fixed

2022-06-13 13:32 UTC, merged